### ISSUE TITLE
Về dữ liệu huấn luyện

### ISSUE THREAD

**Issue by Luvata** [mtb-hust/Poem-Generator#1]
Chào Trường, cảm ơn bạn và team đã public model về sinh thơ này, mình đang thử và sinh được nhiều bài thơ rất vui =))

Mình muốn hỏi thêm thông tin về bộ dữ liệu huấn luyện mô hình này vì trong README chưa ghi có, cụ thể gồm:
- (1) Độ lớn: Số lượng (về gb) để train mô hình này là bao nhiêu gb thơ
- (2) Source: Nguồn thơ bạn crawl từ nguồn nào, 100% là thơ người làm hay có thơ tổng hợp tự động ?
- (3) Training: Bạn huấn luyện model trong thời gian bao lâu, với phần cứng như thế nào ?

Một lần nữa cảm ơn team Trường đã public model này 🥇

**Comment by mtb-hust** [comment]
Dear thanhLV.
1. Số lượng GB thơ cả team train là :)) cỡ 25/1024 GB, lâu rồi không động nên mình ko nhớ cụ thể. Nhưng đó là data cho ver public này, con một số version cải tiến hơn với data nhiều hơn (đáng kể) thì đang trong quá trình phát triển.
2. Nguồn crawl của mình từ thi viện và rất nhiều hội nhóm facebook. Cơ bản thơ đã khá sạch nên cũng chỉ hơi mất công process một chút
3. Model train trên colab pro Tesla V100 trong khoảng 2-3 ngày gì đó cho từng cái. Mình không làm task train nên nhớ mang máng thế!
Đây là version public theo kiểu hidden, để chuẩn bị cho bản release chính thức, cả team đang làm việc để có những kết quả tốt hơn! 
Rất cảm ơn thanhLV vì đã sử dụng và có vẻ thích thú nó 👍

**Comment by Luvata** [comment]
25/1024gb là 25GB huấn luyện hả bạn ?
Còn 1 điều nữa mình quên chưa hỏi, data thơ để training chỉ là thơ lục bát đúng không ?

**Comment by mtb-hust** [comment]
25 mb chỉ là thơ lục bát sao đấy, mình quên không để ý cụ thể nhưng tầm đó cho version này. Các version sau thì nó sẽ ngon và ổn định hơn, và chắc chắn có thú vị hơn như gen thoe chủ đề, keywords. Bên mình vẫn đang tích cực làm việc!

**Comment by Luvata** [comment]
Cảm ơn bạn đã chia sẻ !
